version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./envs/dev.env
    ports:
      - "3001:3001"
